wallpaper {
    monitor = DP-1
    path = /home/moonixiali/Documents/art/Wallpapers/dusk2.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-2
    path = /home/moonixiali/Documents/art/Wallpapers/dusk2.jpg
    fit_mode = cover
}
ipc = on
splash = true
